/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop2.lecture;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import oop2.main.User;

/**
 *
 * @author 이민우
 */
public class All_Stu_Bill extends javax.swing.JFrame {
    ArrayList<String> slist = new ArrayList<>();
    String nowId;
    String text = "euc-kr";
    /**
     * Creates new form All_Stu_Bill
     */
    public All_Stu_Bill(String id) {
        initComponents();
        all_stu_bill.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.nowId = id;
        getTable(); // 학생 정보 테이블 출력
    }
    
    //학생 정보 테이블에 입력
    public void getTable() {
        getSlist();
        String filename;
        String str;
        String[] key;
        File f;
        User u = new User();
        DefaultTableModel table = (DefaultTableModel) all_stu_bill.getModel();
        try {
            for (int i = 0; i < slist.size(); i++) {
                int sum = 0;
                filename = String.format("%s.txt", slist.get(i));
                f = new File(filename);
                if(f.exists()){
                    BufferedReader read = new BufferedReader(new InputStreamReader(new FileInputStream(filename), text));
                    while((str =read.readLine())!= null){
                        key = str.split("/");
                        sum += Integer.parseInt(key[3]); //학점 더하기
                    }
                    Object[] list = {slist.get(i), u.searchName('S', slist.get(i)), Integer.toString(sum), Integer.toString(sum*10000) };
                    //학생 ID, 학생 이름, 총 학점, 총 수강료
                    table.addRow(list);
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(All_Stu_Bill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(All_Stu_Bill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(All_Stu_Bill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //학생 학번 읽어서 리스트에 저장
    public void getSlist(){
        String str;
        String[] key;
        slist.clear(); //리스트 초기화
        try {
            BufferedReader read = new BufferedReader(new InputStreamReader(new FileInputStream("student.txt"),text));
            while((str = read.readLine())!= null){
                key = str.split("/");
                slist.add(key[0]); //학생에 저장되어있는 학번 추가
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(All_Stu_Bill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(All_Stu_Bill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(All_Stu_Bill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //bill.txt에 학번이 있는지 찾기
    public boolean checkBill() throws FileNotFoundException, IOException, UnsupportedEncodingException{
        String str;
        boolean check = false;
        BufferedReader read = new BufferedReader(new InputStreamReader(new FileInputStream("bill.txt"),text));
        while((str = read.readLine()) != null){
            if(num.getText().equals(str))
                check = true; // 학번이 있으면 true
        }
        return check;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        all_stu_bill = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        grade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        goback = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        all_stu_bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "학번", "이름", "신청 학점", "수강료"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        all_stu_bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                all_stu_billMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(all_stu_bill);

        jLabel1.setText("이름");

        jLabel2.setText("학번");

        num.setEditable(false);

        name.setEditable(false);

        jLabel3.setText("신청 학점");

        grade.setEditable(false);

        jLabel4.setText("수강료");

        price.setEditable(false);

        goback.setText("뒤로가기");
        goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel5.setText("수강료 청구서 발급");

        edit.setText("발급");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(edit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(goback, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(price, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(grade, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(num, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goback))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void all_stu_billMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_all_stu_billMouseClicked
        // TODO add your handling code here:
        int row = all_stu_bill.getSelectedRow();
        num.setText((String) all_stu_bill.getValueAt(row, 0));
        name.setText((String) all_stu_bill.getValueAt(row, 1));
        grade.setText((String) all_stu_bill.getValueAt(row, 2));
        price.setText((String) all_stu_bill.getValueAt(row, 3));
    }//GEN-LAST:event_all_stu_billMouseClicked

    //청구서 등록
    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        FileOutputStream file;
        boolean check;
        try {
            check = checkBill(); //청구서가 있는지 확인
            if (!check) {
                file = new FileOutputStream("bill.txt", true); //청구서 파일 열기
                OutputStreamWriter output = new OutputStreamWriter(file, text);
                BufferedWriter writer = new BufferedWriter(output);
                String l = String.format("%s%n",num.getText() );//학번 저장
                writer.write(l);
                writer.close();
                showMessageDialog(null, name.getText() + "님의 청구서 발급이 완료되었습니다.");
            } else
                showMessageDialog(null,name.getText()+"님의 청구서가 이미 발급 되었습니다.");
            num.setText(" ");
            name.setText(" ");
            grade.setText(" ");
            price.setText(" ");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(All_Stu_Bill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(All_Stu_Bill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(All_Stu_Bill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editActionPerformed

    //뒤로가기
    private void gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackActionPerformed
        try {
            // TODO add your handling code here:
            Lecture_Main_Frame l = new Lecture_Main_Frame(nowId,'G');
            l.setVisible(true);
            dispose();
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(All_Stu_Bill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(All_Stu_Bill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gobackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable all_stu_bill;
    private javax.swing.JButton edit;
    private javax.swing.JButton goback;
    private javax.swing.JTextField grade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField num;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
