/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop2.login;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oop2.professor.Professor_Main_Frame;
import static javax.swing.JOptionPane.showMessageDialog;
import oop2.lecture.Lecture_Main_Frame;
import oop2.school.School_Main_Frame;
import oop2.student.Student_Main_Frame;
import oop2.main.User;
/**
 *
 * @author 하태형
 */
public class Login_Frame extends javax.swing.JFrame {
    User user = new User();
    String[] nowUser;
    String nowName;
    String text = "euc-kr";
    /**
     * Creates new form Login_Frame
     */
    public Login_Frame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        PW_Field = new javax.swing.JPasswordField();
        ID_Field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Login_Button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(401, 267));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PW_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 141, -1));

        ID_Field.setToolTipText("");
        getContentPane().add(ID_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 141, -1));

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 0, 28)); // NOI18N
        jLabel1.setText("대학 정보 시스템");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("아이디");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("비밀번호");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        Login_Button.setText("로그인");
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Login_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 77, 52));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\drush\\Desktop\\University_System\\src\\main\\java\\oop2\\login\\530605_335239_856.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        // TODO add your handling code here: 
        String id_Field = ID_Field.getText(); //ID 필드에서 값 받아오기
        String pw_Field = new String(PW_Field.getPassword());//PW 필드에서 값 받아오기
        char a;
        BufferedReader reader = null;
        String str;
        String[] key;
        try {
            if (ID_Field.getText().isEmpty() || PW_Field.getText().isEmpty()) {//입력받지 않았을 때
                showMessageDialog(null, "아이디 또는 비밀번호를 입력하여주세요.");
            } else {
                a = id_Field.charAt(0); //아이디를 입력하는 직군을 구분하기 위한 이니셜 저장
                if (a == 'P') { //아이디 고유 문자가 p -> 교수
                    reader = new BufferedReader(new InputStreamReader(new FileInputStream("professor.txt"), text));//읽을 파일 열기
                    while ((str = reader.readLine()) != null) { //마지막 문장이 아닐동안 반복 
                        key = str.split("/"); // "/"를 이용해 배열에 저장
                        //table에 따라 [0] : id, [1] : name, [2] : pw, [3] : peopleNum, [4] : departMent
                        if (key[0].equals(id_Field)) { //입력받은 아이디가 문장안에 있을시
                            if (key[2].equals(pw_Field)) { //비밀번호가 같은지 검사
                                Professor_Main_Frame pro = new Professor_Main_Frame(key[0]);
                                //맞으면 해당 메뉴 출력
                                pro.setVisible(true);
                                dispose();//현재창은 닫기
                            }
                        }
                    }
                    
                } else if (a == 'S') {//아이디 고유 문자가 s -> 학생
                    reader = new BufferedReader(new InputStreamReader(new FileInputStream("student.txt"), text));
                    while ((str = reader.readLine()) != null) {
                        if (str.contains(id_Field)) {
                            key = str.split("/");
                            if (key[2].equals(pw_Field)) {
                                Student_Main_Frame stu = new Student_Main_Frame(key[0], a); //임시로 로그인 시 사용자 정보를 넘김
                                stu.setVisible(true);
                                //nowName = key[1];
                                //new Student_Main_Frame(nowName).setVisible(true);
                                dispose();
                            } 
                        }
                    }
                } else if (a == 'H') {//아이디 고유 문자가 h -> 학사
                    reader = new BufferedReader(new InputStreamReader(new FileInputStream("school.txt"),text));
                    while ((str = reader.readLine()) != null) {
                        if (str.contains(id_Field)) {
                            key = str.split("/");
                            if (key[2].equals(pw_Field)) {
                                School_Main_Frame sch = new School_Main_Frame(key[0], a);
                                sch.setVisible(true);
                                dispose();
                            }
                        }
                    }
                } else if (a == 'G') {//아이디 고유 문자가 g -> 수업
                    reader = new BufferedReader(new InputStreamReader(new FileInputStream("lecture.txt"), text));
                    while ((str = reader.readLine()) != null) {
                        if (str.contains(id_Field)) {
                            key = str.split("/");
                            if (key[2].equals(pw_Field)) {
                                Lecture_Main_Frame lec = new Lecture_Main_Frame(key[0], a);
                                lec.setVisible(true);
                                dispose();
                            } 
                        }
                    }
                } else {
                   JOptionPane.showMessageDialog(null, "아이디 또는 비밀번호가 잘못 입력 되었습니다.\n" + "아이디와 비밀번호를 정확히 입력해 주세요..", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (FileNotFoundException ex) { //파일이 발견되지 않았을 때 예외처리
            Logger.getLogger(Login_Frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Login_Frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Login_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Login_ButtonActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID_Field;
    private javax.swing.JButton Login_Button;
    private javax.swing.JPasswordField PW_Field;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
